version: '3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftpd_server:
    image: localsnet/pureftpd:1.1
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "${PWD}/data/home:/home" # Workaround visibility. After creating user in container and accessed one, need rm -rf ./home/ftpusers/ on docker host to visibility in users dirs.
      - "${PWD}/data/etc/ssl/private:/etc/ssl/private" #Need generate certs by openssl and put in this directory
      - "${PWD}/data/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      # FTP_USER_NAME: 
      #FTP_USER_PASS: 
      #FTP_USER_HOME: /home/ftp1
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
    command: "bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb --tls 3 -E -j -R -P <YOUR_DOMAIN> -d"
